# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afcec430eaf8244ae5115443da664ea74bd6b01307cbf383d2ac168ee462118ac0dad1a930334983e977e02fbdc56988813b873252c7e6696a3459234d6ca309

test:
  secret_key_base: a1ea266f7e780b5e32b1c928507efa4062c3d0f8068616e669cb6fe00d6e816d558c85a47562da9ef126746cef7c58dfa5a333e3449e1766662fbab015d0b4ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
